version: '3.8'
services:
  chrome:
    image: chrome-docker
    build:
      context: .
      dockerfile: Dockerfile.chrome
    environment:
      - DISPLAY=:99
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: >
      sh -c "Xvfb :99 -screen 0 1280x720x24 -nolisten tcp & 
             x11vnc -display :99 -forever -nopw -rfbport 5900 -verbose -shared &
             google-chrome --no-sandbox --disable-gpu --disable-software-rasterizer --disable-dev-shm-usage --disable-accelerated-2d-canvas --disable-accelerated-jpeg-decoding --disable-accelerated-mjpeg-decode --disable-accelerated-video-decode --no-first-run --headless=new"
    shm_size: '512m'
  novnc:
    image: theasp/novnc:latest
    ports:
      - "6080:6080"
    environment:
      - VNC_SERVER=127.0.0.1:5900
      - RESOLUTION=1280x720
      - RUN_XTERM=no
      - RUN_FLUXBOX=no
    command: >
      sh -c "websockify --web /usr/share/novnc 6080 127.0.0.1:5900"